### ISSUE TITLE
How to register for the online platform?

### ISSUE THREAD

**Issue by buzzdev** [opengasmonitor/gasmonitor-firmware#1]
Szia Laszlo,
i am trying to register for the online platform at https://opengasmonitor.org but there's no login, registration or something similar.
How do i actually get my data to the platform?

Thanks/Koeszi!

**Comment by laszlotar** [comment]
Hi! Thank you for getting in touch. The platform is in a kind of closed beta right now. The registration will be done through the app, however it was disabled last time to make app review processes faster and less vigorous.

I did some work this week on the web based interface, so you can use this website to sign up: https://gasmonitor.cloud
You will still need to use the app to add your monitor, as I have yet to implement this feature on the website.

Have a look at this article on how to configure the monitor you built: https://www.hackster.io/opengasmonitor/build-an-open-gas-monitor-sensor-device-ad09a0

Let me know if you have any issues!

Best,

Laszlo

**Comment by buzzdev** [comment]
Great! It worked flawlessly.
Many thanks.
My gas meter counter is a zigbee device, not a nodemcu.
So i am now reading your code and setting it up by me, to send the required JSON from HASS.
